@baseURL = http://localhost:3001

### Get all piercings (ou List all piercings)
GET {{baseURL}}/piercings

### Create a new piercing
POST {{baseURL}}/piercings
Content-Type: application/json

{
  "name": "New piercing",
  "price": 1800.0
}

### Update a piercing by ID
PUT {{baseURL}}/piercings/1
Content-Type: application/json

{
  "name": "Updated piercing",
  "price": 2200.0
}

### Delete a piercing by ID
DELETE {{baseURL}}/piercings/1








# Header name must be a valid HTTP token ["{"]